version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: ember-cli
    versions:
    - 3.25.0
    - 3.25.3
    - 3.26.0
  - dependency-name: eslint
    versions:
    - 7.19.0
    - 7.20.0
    - 7.23.0
    - 7.24.0
  - dependency-name: ember-cli-babel
    versions:
    - 7.23.1
    - 7.25.0
    - 7.26.1
    - 7.26.2
    - 7.26.3
  - dependency-name: ember-auto-import
    versions:
    - 1.11.2
  - dependency-name: eslint-plugin-ember
    versions:
    - 10.2.0
    - 10.3.0
  - dependency-name: ember-cli-htmlbars
    versions:
    - 5.3.2
    - 5.4.0
    - 5.6.0
    - 5.6.2
    - 5.6.3
    - 5.6.4
    - 5.6.5
    - 5.7.0
  - dependency-name: ember-source
    versions:
    - 3.25.0
    - 3.25.1
    - 3.25.3
  - dependency-name: ember-template-lint
    versions:
    - 2.18.0
    - 2.18.1
    - 2.19.0
    - 2.20.0
    - 2.21.0
    - 3.0.0
    - 3.1.1
